workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.example.distancecamera"
      java: 11
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Get Flutter dependencies
        script: |
          # Skip if not a Flutter project
          if [ -f "pubspec.yaml" ]; then
            flutter packages pub get
          fi
      - name: Make gradlew executable
        script: |
          chmod +x ./gradlew
      - name: Build APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/mapping.txt
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: false